# Basic
title: 陈东兴
subtitle: 个人站
description: 欢迎来到我的个人站~
# 头像里面的标题
avatarTitle: gakileen
# 头像里面的描述
avatarDesc: Java / Python / Scala
url: ""

# Comment
comment:
    # disqus: gakileen
    duoshuo: gakileen 

# Social
social:
    github: gakileen


permalink: /:year/:month/:title/
# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}      
    - {title: 关于我, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate]
paginate: 20
paginate_path: "page/:num/"

# Build settings
markdown: kramdown
theme: minima